defaults:
  - location: local
  - augmentations: resizing
  - dataset: francecrops_nano
  - _self_

visualizer:
  sample: None
  overlay: true
  classid: 0
  bands: []
  seed: None
  function: "plotbeforeandafter"

training:
  n_samples_per_group: 4
  
