defaults:
  - location: local
  - augmentations: resizing
  - dataset: francecrops_nano
  - _self_

visualizer:
  sample: 0
  overlay: true
  classid: 1
  bands: []
  seed: 2025
  function: "plotbeforeandafter"

training:
  n_samples_per_group: 4
  
