name: s2_agri_100

ssl_data_dir: ${location.base_path}/${dataset.name}/contrast_dataset
validation_data_dir: ${location.base_path}/${dataset.name}/validation_dataset
train_data_dir: ${location.base_path}/${dataset.name}/train_dataset
num_train_subsets: 1
test_data_dir: ${location.base_path}/${dataset.name}/test_dataset

percentiles: [
  [0.0001, 0.0300, 0.0155, 0.0536, 0.1169, 0.1322, 0.1335, 0.1479, 0.0978, 0.0508],
  [0.1265, 0.1679, 0.1981, 0.2238, 0.3797, 0.4677, 0.4917, 0.5050, 0.3605, 0.2660]
]

normalize: true
n_channels: 10
group_size: 25
n_timesteps: 24