name: ts_ssl_cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.4
  - scikit-learn
  - pandas
  - pip
  - pip:
    - hydra-core==1.3.2
    - mmap-ninja
    - lightly
    - torchinfo
    - -e . 