name: ts_ssl
channels:
  - pytorch
  - conda-forge
  - rapidsai
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.4
  - pytorch-cuda=12.4
  - scikit-learn
  - pandas
  - pip
  - pip:
    - cuml-cu12==24.12.0
    - hydra-core==1.3.2
    - mmap-ninja
    - lightly
    - torchinfo
    - -e .