name: masking

views_sampling_strategy: "group"

view1:
  transforms:
    jittering:
      _target_: ts_ssl.data.augmentations.Jittering
      sigma: 0.03
    time_masking:
      _target_: ts_ssl.data.augmentations.TimeMasking
      num_masks: 3
      mask_length: 0.1
      
view2:
  transforms:
    jittering:
      _target_: ts_ssl.data.augmentations.Jittering
      sigma: 0.03
    time_masking:
      _target_: ts_ssl.data.augmentations.TimeMasking
      num_masks: 3
      mask_length: 0.1 