defaults:
  - location: local
  - augmentations: resizing
  - dataset: francecrops_nano
  - _self_

visualizer:
  sample: None # positive int 
  overlay: true
  classid: 0 # [0,19]
  bands: []
  seed: None # positive int
  function: "plotbeforeandafter"

training:
  n_samples_per_group: 4
  batch_size: 1024
  num_workers: 4
  iterations: 1

  
