iterations: 10

mmap:
  name: francecrops_20k_mmap
  dataset_type: mmap_ninja

  ssl_data: ${location.base_path}/${loaddatautil.mmap.name}/contrast
  validation_data: ${location.base_path}/${loaddatautil.mmap.name}/validation
  train_data: ${location.base_path}/${loaddatautil.mmap.name}/train
  test_data: ${location.base_path}/${loaddatautil.mmap.name}/test

  percentiles: [
    [105.0, 192.0, 388.0, 240.0, 664.0, 1257.0, 1393.0, 1438.0, 1524.0, 1638.0, 1183.0, 569.0],
    [1272.0, 1543.0, 2008.0, 2617.0, 3022.0, 4322.0, 5217.0, 5451.0, 5438.0, 5377.0, 4546.0, 3611.0]
  ]

  normalize: true
  n_channels: 12
  group_size: 100
  n_timesteps: 60

arrow:
  name: francecrops_nano
  dataset_type: huggingface

  ssl_data:
    path: saget-antoine/francecrops
    cache_dir: ${location.base_path}/${loaddatautil.arrow.name}
    split: train
  validation_data:
    path: saget-antoine/francecrops
    cache_dir: ${location.base_path}/${loaddatautil.arrow.name}
    split: train
  test_data:
    path: saget-antoine/francecrops
    cache_dir: ${location.base_path}/${loaddatautil.arrow.name}
    split: train
  train_data:
    path: saget-antoine/francecrops
    cache_dir: ${location.base_path}/${loaddatautil.arrow.name}
    split: train


  percentiles: [
    [105.0, 192.0, 388.0, 240.0, 664.0, 1257.0, 1393.0, 1438.0, 1524.0, 1638.0, 1183.0, 569.0],
    [1272.0, 1543.0, 2008.0, 2617.0, 3022.0, 4322.0, 5217.0, 5451.0, 5438.0, 5377.0, 4546.0, 3611.0]
  ]

  normalize: true
  n_channels: 12
  group_size: 100
  n_timesteps: 60