defaults:
  - config
  - _self_

output_dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${dataset.name}_${model.name}_${augmentations.name}/eval

eval:
  checkpoint_path: null
  samples_per_class: [5, 10, 20, 50, 100]
  seed: ${seed}
  use_raw_features: false
  batch_size: 128
  downstream_models:
    lr:
      max_iter: 2000
      tol: 1e-5
      C: 1.0
      n_jobs: -1  # Only used for sklearn
    # sklearn:
    #   _target_: sklearn.linear_model.LogisticRegression
    #   max_iter: 2000
    #   tol: 1e-5
    #   C: 1.0
    #   n_jobs: -1 